In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [4]:
X = pd.read_parquet("../data/processed/luad_X.parquet")
labels = pd.read_csv("../data/processed/luad_labels.csv")

y = labels["label"]

X.shape, labels.shape

((574, 20530), (574, 3))

### Retrain to get learned coefficients

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)

In [6]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    random_state=42,
)

model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=5000, random_state=42)

### Extract gene coeffecients

In [ ]:
# coef is the weight of a gene
coefs = model.coef_[0]

importance = pd.DataFrame({
    "gene": X.columns,
    "coef": coefs,
    "abs_coef": np.abs(coefs),
})

importance.head()

        gene      coef  abs_coef
0  ARHGEF10L  0.001692  0.001692
1      HIF3A  0.003501  0.003501
2      RNF17 -0.004475  0.004475
3      RNF10  0.002638  0.002638
4      RNF11 -0.004821  0.004821

In [9]:
top_tumor = importance.sort_values("coef", ascending=False).head(20)
top_tumor

           gene      coef  abs_coef
14760   DEFB127  0.034193  0.034193
17964    FKSG73  0.034193  0.034193
15197   SNORA38  0.022417  0.022417
2404    C7orf34  0.021256  0.021256
11789  SLC22A24  0.019950  0.019950
3355   HNRNPCL1  0.019788  0.019788
12758     CCL16  0.019760  0.019760
3591       CDX4  0.019644  0.019644
15327  C22orf42  0.018269  0.018269
3944    KBTBD13  0.018178  0.018178
12509   C3orf22  0.017680  0.017680
502      CXorf1  0.017562  0.017562
7410     NT5C1A  0.017241  0.017241
18939    FKSG83  0.016224  0.016224
14597      PMP2  0.016162  0.016162
19047    KDELR3  0.016086  0.016086
15446      MUC6  0.015965  0.015965
2440      IL23R  0.015816  0.015816
4381     MAGEB4  0.015785  0.015785
9724       ADM2  0.015671  0.015671

In [10]:
top_normal = importance.sort_values("coef", ascending=True).head(20)
top_normal

            gene      coef  abs_coef
9759    SCARNA23 -0.032378  0.032378
15841  LOC643923 -0.022097  0.022097
10398       CSN3 -0.021872  0.021872
3403        IL13 -0.020622  0.020622
12303      EPB42 -0.020221  0.020221
11292     FAM71A -0.018919  0.018919
11102     BARHL1 -0.018595  0.018595
16721  C20orf201 -0.017820  0.017820
7970       OR6K3 -0.017556  0.017556
6946      ZFATAS -0.017093  0.017093
4682         CRH -0.016587  0.016587
10231     CHRNA4 -0.016029  0.016029
4512      SC4MOL -0.015606  0.015606
12936  LOC441294 -0.015375  0.015375
10283     ANKRD2 -0.015189  0.015189
2158     TAS2R30 -0.015009  0.015009
2515      ACTRT2 -0.014974  0.014974
20075  LOC285205 -0.014847  0.014847
18629     PPBPL2 -0.014709  0.014709
11694       UTP3 -0.014507  0.014507

In [11]:
importance.sort_values("abs_coef", ascending=False).to_csv(
    "../data/processed/logistic_gene_importance.csv",
    index=False,
)

### Compare model coefficients with tumor-vs-normal expression difference

In [14]:
X_labeled = X.copy()
X_labeled["sample_type"] = labels["sample_type"].values
X_labeled["label"] = labels["label"].values

X_labeled[["sample_type", "label"]].head()

gene            sample_type  label
TCGA-69-7978-01       tumor    1.0
TCGA-62-8399-01       tumor    1.0
TCGA-78-7539-01       tumor    1.0
TCGA-50-5931-11      normal    0.0
TCGA-73-4658-01       tumor    1.0

In [15]:
# compute mean expression in tumor and normal

gene_cols = X.columns

tumor_mean = X_labeled[X_labeled["sample_type"] == "tumor"][gene_cols].mean()
normal_mean = X_labeled[X_labeled["sample_type"] == "normal"][gene_cols].mean()

In [16]:
# Compute difference in gene expression in tumor vs normal

diff = tumor_mean - normal_mean

In [17]:
gene_report = importance.copy()

gene_report["tumor_mean"] = gene_report["gene"].map(tumor_mean)
gene_report["normal_mean"] = gene_report["gene"].map(normal_mean)
gene_report["tumor_minus_normal"] = gene_report["gene"].map(diff)

gene_report.head()

        gene      coef  abs_coef  tumor_mean  normal_mean  tumor_minus_normal
0  ARHGEF10L  0.001692  0.001692    9.540719     9.517868            0.022851
1      HIF3A  0.003501  0.003501    6.877338     9.041775           -2.164437
2      RNF17 -0.004475  0.004475    0.551699     0.471249            0.080450
3      RNF10  0.002638  0.002638   11.770312    11.738858            0.031455
4      RNF11 -0.004821  0.004821   10.895561    11.507475           -0.611914

In [23]:
gene_report.sort_values("abs_coef", ascending=False).head(20)[
    ["gene", "coef", "tumor_mean", "normal_mean", "tumor_minus_normal"]
]

            gene      coef  tumor_mean  normal_mean  tumor_minus_normal
17964     FKSG73  0.034193    0.005812     0.000000            0.005812
14760    DEFB127  0.034193    0.001052     0.016125           -0.015073
9759    SCARNA23 -0.032378    0.001128     0.011892           -0.010764
15197    SNORA38  0.022417    0.005109     0.000000            0.005109
15841  LOC643923 -0.022097    0.065920     0.236015           -0.170095
10398       CSN3 -0.021872    0.042772     0.061217           -0.018445
2404     C7orf34  0.021256    0.257439     0.228693            0.028746
3403        IL13 -0.020622    0.780545     1.601625           -0.821080
12303      EPB42 -0.020221    0.157139     1.466269           -1.309130
11789   SLC22A24  0.019950    0.013990     0.011334            0.002656
3355    HNRNPCL1  0.019788    0.041830     0.000000            0.041830
12758      CCL16  0.019760    0.808234     1.584759           -0.776526
3591        CDX4  0.019644    0.001002     0.000000            0.001002
11292     FAM71A -0.018919    0.381267     1.997300           -1.616033
11102     BARHL1 -0.018595    0.075210     0.114193           -0.038983
15327   C22orf42  0.018269    0.025644     0.033834           -0.008190
3944     KBTBD13  0.018178    0.102786     0.186708           -0.083922
16721  C20orf201 -0.017820    0.930721     1.800334           -0.869613
12509    C3orf22  0.017680    0.050921     0.025669            0.025251
502       CXorf1  0.017562    0.126480     0.874453           -0.747973

In [18]:
gene_report.sort_values("coef", ascending=False).head(20)

,gene,coef,abs_coef,tumor_mean,normal_mean,tumor_minus_normal
14760,DEFB127,0.034193,0.034193,0.001052,0.016125,-0.015073
17964,FKSG73,0.034193,0.034193,0.005812,0.000000,0.005812
15197,SNORA38,0.022417,0.022417,0.005109,0.000000,0.005109
2404,C7orf34,0.021256,0.021256,0.257439,0.228693,0.028746
11789,SLC22A24,0.019950,0.019950,0.013990,0.011334,0.002656
3355,HNRNPCL1,0.019788,0.019788,0.041830,0.000000,0.041830
12758,CCL16,0.019760,0.019760,0.808234,1.584759,-0.776526
3591,CDX4,0.019644,0.019644,0.001002,0.000000,0.001002
15327,C22orf42,0.018269,0.018269,0.025644,0.033834,-0.008190
3944,KBTBD13,0.018178,0.018178,0.102786,0.186708,-0.083922
12509,C3orf22,0.017680,0.017680,0.050921,0.025669,0.025251
502,CXorf1,0.017562,0.017562,0.126480,0.874453,-0.747973
7410,NT5C1A,0.017241,0.017241,1.133291,0.458175,0.675117
18939,FKSG83,0.016224,0.016224,0.033795,0.072334,-0.038539
14597,PMP2,0.016162,0.016162,0.414556,0.835876,-0.421321
19047,KDELR3,0.016086,0.016086,9.873483,7.822210,2.051273
15446,MUC6,0.015965,0.015965,4.134521,3.547847,0.586673
2440,IL23R,0.015816,0.015816,1.092426,0.990171,0.102255
4381,MAGEB4,0.015785,0.015785,0.028485,0.006342,0.022142
9724,ADM2,0.015671,0.015671,8.139807,4.753285,3.386523

In [19]:
gene_report.sort_values("coef", ascending=True).head(20)

,gene,coef,abs_coef,tumor_mean,normal_mean,tumor_minus_normal
9759,SCARNA23,-0.032378,0.032378,0.001128,0.011892,-0.010764
15841,LOC643923,-0.022097,0.022097,0.065920,0.236015,-0.170095
10398,CSN3,-0.021872,0.021872,0.042772,0.061217,-0.018445
3403,IL13,-0.020622,0.020622,0.780545,1.601625,-0.821080
12303,EPB42,-0.020221,0.020221,0.157139,1.466269,-1.309130
11292,FAM71A,-0.018919,0.018919,0.381267,1.997300,-1.616033
11102,BARHL1,-0.018595,0.018595,0.075210,0.114193,-0.038983
16721,C20orf201,-0.017820,0.017820,0.930721,1.800334,-0.869613
7970,OR6K3,-0.017556,0.017556,0.188966,1.937473,-1.748507
6946,ZFATAS,-0.017093,0.017093,0.178941,0.218149,-0.039209
4682,CRH,-0.016587,0.016587,0.422716,1.599042,-1.176327
10231,CHRNA4,-0.016029,0.016029,0.569037,2.169247,-1.600210
4512,SC4MOL,-0.015606,0.015606,10.550266,11.703531,-1.153264
12936,LOC441294,-0.015375,0.015375,6.006308,5.621025,0.385283
10283,ANKRD2,-0.015189,0.015189,1.418885,2.065337,-0.646453
2158,TAS2R30,-0.015009,0.015009,0.185475,0.234010,-0.048535
2515,ACTRT2,-0.014974,0.014974,0.028332,0.040964,-0.012633
20075,LOC285205,-0.014847,0.014847,0.509321,1.206273,-0.696952
18629,PPBPL2,-0.014709,0.014709,0.070004,0.118436,-0.048432
11694,UTP3,-0.014507,0.014507,9.396891,9.619503,-0.222612

In [20]:
top_up_in_tumor = gene_report.sort_values(
    "tumor_minus_normal",
    ascending=False,
).head(20)

top_up_in_normal = gene_report.sort_values(
    "tumor_minus_normal",
    ascending=True,
).head(20)

In [21]:
top_up_in_tumor[["gene", "coef", "tumor_mean", "normal_mean", "tumor_minus_normal"]]

           gene      coef  tumor_mean  normal_mean  tumor_minus_normal
17892    FAM83A  0.012736   10.108718     3.877571            6.231147
4238    COL11A1  0.004480    8.157597     2.305314            5.852283
19773      CST1  0.002443    6.984317     1.136517            5.847800
3948   LOC84740  0.014810    9.063464     3.837763            5.225702
3296    CYP24A1  0.010676    8.355195     3.144085            5.211110
12960     MMP11  0.008202   10.158472     5.003664            5.154808
7271     ABCA12  0.010460    6.413655     1.416124            4.997531
8074        CA9  0.006049    6.478163     1.553093            4.925069
12962     MMP13  0.004963    6.702057     1.821312            4.880745
12041  PPP1R14D  0.007169    5.952637     1.149886            4.802750
13593     SYT12  0.011963    7.544361     2.741873            4.802488
16635   TMPRSS4  0.010750   10.225824     5.427471            4.798353
2596      PTPRH  0.010487    7.055646     2.287119            4.768527
15769    SPINK1  0.010328    8.142274     3.388986            4.753287
11727      SPP1  0.013339   12.460326     7.720673            4.739654
9046       MMP1  0.000670    9.062762     4.407617            4.655145
19117     PRAME -0.001766    5.596508     0.944536            4.651972
2835    COL10A1  0.010509    9.375096     4.727376            4.647720
3873     CRABP2  0.005448   10.532637     5.896254            4.636383
15941     PITX2  0.001287    4.877770     0.370405            4.507365

In [22]:
top_up_in_normal[["gene", "coef", "tumor_mean", "normal_mean", "tumor_minus_normal"]]

           gene      coef  tumor_mean  normal_mean  tumor_minus_normal
19926     SFTPC  0.001357   10.406971    18.965454           -8.558483
8612     SLC6A4 -0.001695    2.955707    10.926241           -7.970534
19134    CLDN18  0.000161    7.404636    14.457229           -7.052593
8420       AGER -0.002465    8.652601    15.411381           -6.758781
6791      ITLN2 -0.001741    2.222745     8.980227           -6.757482
3177       LGI3  0.002372    4.206939    10.844725           -6.637786
4524   C13orf36 -0.006967    1.828323     8.291746           -6.463423
9539      FABP4 -0.000530    5.167863    11.330927           -6.163064
11461      HBA1 -0.001570    5.565666    11.552702           -5.987035
14114     GPM6A  0.000040    4.249797    10.215029           -5.965232
10803   CD300LG  0.006015    2.210423     8.105636           -5.895212
15759     UPK3B -0.001338    5.390495    11.279400           -5.888905
8085        CA4  0.001313    3.615104     9.457246           -5.842142
5013    SCGB1A1 -0.003849    7.473163    13.263920           -5.790758
10282    ANKRD1 -0.000367    4.186823     9.909415           -5.722592
18434      WIF1 -0.002098    6.165853    11.599759           -5.433906
4654       CPB2 -0.004729    4.132280     9.510944           -5.378664
9578       GKN2  0.000994    4.556273     9.933702           -5.377429
13265     CNTN6 -0.000642    2.889496     8.259534           -5.370038
7054    SOSTDC1  0.001815    3.757262     9.051464           -5.294203